# Site settings
title: Shiveswarran Ratneswaran
email: shiveswarran.22@cse.mrt.ac.lk
description: Academic webpage of Shiveswarran
baseurl: ""
url: "https://shiveswarran.github.io"
affiliation: I am postgraduate student at the University of Moratuwa, Sri Lanka.

# Google analytics ID
#google_analytics: UA-286355308-1

# Location info. (shown in footer)
location: >
  Coordinates: <br/>
  Dept. Computer Science and Engineering<br/>
  University of Moratuwa<br/>
  Katubedda 10400<br/>
  Sri Lanka<br/>

# Contact info. (shown in footer)
contact: >
    Contact via email: <a href="mailto:shiveswarran.22@cse.mrt.ac.lk" target="_blank">shiveswarran.22@cse.mrt.ac.lk</a><br/> 
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use this site as a template</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: publications
  - name: Presentations
  - name: software
  
# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag